/**
 * An InputDetails object is generated by the InputDelegate, and contains relevant information about user input, such as controller buttons, keyboard keys, etc.
 */

/**************************************************************************

Filename    :   InputDetails.as

Copyright   :   Copyright 2011 Autodesk, Inc. All Rights reserved.

Use of this software is subject to the terms of the Autodesk license
agreement provided at the time of installation or download, or which
otherwise accompanies this software in either electronic or hard copy form.

**************************************************************************/

package scaleform.clik.ui {
    
    public class InputDetails {
    
    // Constants:
    // Public Properties:
        public var type:String;
        public var code:Number;
        public var value:*;
        public var navEquivalent:String;
        public var controllerIndex:uint;
        public var ctrlKey:Boolean;
        public var altKey:Boolean;
        public var shiftKey:Boolean
        
    // Private Properties:
    // Initialization:
        public function InputDetails(type:String, code:Number, value:*, navEquivalent:String = null, controllerIndex:uint = 0, 
                                        ctrlKey:Boolean = false, altKey:Boolean = false, shiftKey:Boolean = false) {
            this.type = type;
            this.code = code;
            this.value = value;
            this.navEquivalent = navEquivalent;
            this.controllerIndex = controllerIndex;
            this.ctrlKey = ctrlKey;
            this.altKey = altKey;
            this.shiftKey = shiftKey;
        }
    
    // Public Methods:
        public function toString():String {
            return  "[InputDetails code=" + code +  ", type=" + type + " value=" + value + ", navEquivalent=" + navEquivalent + 
                    ", controllerIndex=" + controllerIndex + ", ctrlKey=" + ctrlKey + ", altKey=" + altKey + ", shiftKey=" + shiftKey + "]";
        }
        
    // Private Methods:
    
    }
    
}